### PR TITLE
Fixes issues in strict shortlink parsing.

### PR DESCRIPTION
**Pull request by JorgenEvens**

### CODE REVIEW

**Comment by GertSallaerts** [comment]
I'd rather you sanitize the baseUrl and endpoint in the constructor, because now it can still generate links like `https://forwrd.it//r/bla` when there's a trailing slash. Or am I mistaken?

**Comment by JorgenEvens** [comment]
I can only partially sanitize it in the constructor, since it is also used a a prefix for new URLs and this regex effectively removes `https?://`

**Comment by GertSallaerts** [comment]
I guess you'll have to split up the regex?

**Comment by JorgenEvens** [comment]
Fine by me, will split it up.

**Comment by JorgenEvens** [comment]
@Gertt fixed

**Pull request merged**
